name: Publish to hub.docker.com

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Create nightly tag
        # `${GITHUB_REF_NAME/#v}` is the branch or tag name where prefix `v` is removed.
        run: echo "IMAGE_TAG=${GITHUB_REF_NAME/#v}" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: tbartsch/marigold:${{ env.IMAGE_TAG }}