name: Publish to hub.docker.com

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Create nightly tag
        # `${GITHUB_REF_NAME/#v}` is the branch or tag name where prefix `v` is removed.
        run: echo "IMAGE_TAG=${GITHUB_REF_NAME/#v}" >> $GITHUB_ENV
      -
        name: Checkout repo
        uses: actions/checkout@v2.3.4
      -
        name: Install Nix
        uses: cachix/install-nix-action@v15
      -
        name: Install Docker
        uses: docker-practice/actions-setup-docker@master
      -
        name: Build Docker container
        run: |
         docker load < $(nix-build nix/docker.nix)
         docker tag marigold:nightly tbartsch/marigold:nightly_${{ env.IMAGE_TAG }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: tbartsch/marigold:nightly_${{ env.IMAGE_TAG }}